// Populates the final thin decks: N4 advanced/compound particles, and the
// phrase decks (N4 daily/opinion/request, N3 connecting/feelings/formal,
// N2 business/written, N1 formal/nuanced).
// vocab-schema JSON + .js fallback for file://. Run: node build-phrases.js
const fs = require("fs");
const path = require("path");
const DATA = path.join(__dirname, "data");

// rows: [word, reading, romaji, meaning, exJP, exRead, exMean]
const mk = (level, pos) => (r) => ({
  word: r[0], reading: r[1] || "", romaji: r[2] || "", meaning: r[3] || "",
  partOfSpeech: pos, exampleSentence: r[4] || "", exampleReading: r[5] || "",
  exampleMeaning: r[6] || "", level,
});

const DECKS = {
  "n4-particles-advanced": { level: "N4", pos: "Particle", rows: [
    ["のに","","noni","although / even though","勉強したのに、忘れた。","べんきょうしたのに、わすれた。","Although I studied, I forgot."],
    ["ので","","node","because (softer than から)","雨なので、行きません。","あめなので、いきません。","Because it's raining, I won't go."],
    ["でも","","demo","~ or something / even","お茶でも飲みませんか。","おちゃでものみませんか。","Would you like some tea or something?"],
    ["しか〜ない","","shika ~nai","only (with negative)","千円しかない。","せんえんしかない。","I only have a thousand yen."],
    ["だけ","","dake","only / just","一つだけください。","ひとつだけください。","Just one, please."],
    ["ばかり","","bakari","only / nothing but","彼は遊んでばかりいる。","かれはあそんでばかりいる。","He does nothing but play around."],
    ["まで","","made","even (to the extent of)","子供までできる。","こどもまでできる。","Even children can do it."],
    ["までに","","made ni","by (a deadline)","五時までに帰る。","ごじまでにかえる。","I'll be back by five o'clock."],
    ["ながら","","nagara","while (doing two things)","歩きながら話す。","あるきながらはなす。","I talk while walking."],
    ["し","","shi","and (listing reasons)","安いし、おいしい。","やすいし、おいしい。","It's cheap, and tasty too."],
    ["って","","tte","quotative / topic (casual)","田中さんって優しいね。","たなかさんってやさしいね。","Tanaka is kind, isn't he?"],
    ["なら","","nara","if / as for","それなら賛成だ。","それならさんせいだ。","If that's the case, I agree."],
    ["とか","","toka","~ and ~ (examples)","映画とか音楽が好きだ。","えいがとかおんがくがすきだ。","I like movies, music, and so on."],
    ["ぐらい / くらい","","gurai / kurai","about / to the extent of","一時間ぐらいかかる。","いちじかんぐらいかかる。","It takes about an hour."],
    ["ほど","","hodo","to the extent / as ~ as","思ったほど難しくない。","おもったほどむずかしくない。","It's not as hard as I thought."],
    ["さえ","","sae","even","自分の名前さえ書けない。","じぶんのなまえさえかけない。","He can't even write his own name."],
    ["のが / のは","","no ga / no wa","nominalizer (turns a verb into a noun)","泳ぐのが好きだ。","およぐのがすきだ。","I like swimming."],
  ]},

  "n4-particles-compound": { level: "N4", pos: "Particle", rows: [
    ["について","","ni tsuite","about / concerning","趣味について話す。","しゅみについてはなす。","I talk about my hobbies."],
    ["のために","","no tame ni","for the sake of / in order to","家族のために働く。","かぞくのためにはたらく。","I work for my family."],
    ["のように","","no you ni","like / as","鳥のように飛びたい。","とりのようにとびたい。","I want to fly like a bird."],
    ["みたいに","","mitai ni","like (casual)","子供みたいに笑う。","こどもみたいにわらう。","He laughs like a child."],
    ["の代わりに","のかわりに","no kawari ni","instead of","父の代わりに私が行く。","ちちのかわりにわたしがいく。","I'll go instead of my father."],
    ["のおかげで","","no okage de","thanks to (positive)","先生のおかげで合格した。","せんせいのおかげでごうかくした。","Thanks to my teacher, I passed."],
    ["のせいで","","no sei de","because of (negative, blame)","雨のせいで遅れた。","あめのせいでおくれた。","I was late because of the rain."],
    ["によって","","ni yotte","by / depending on","季節によって景色が変わる。","きせつによってけしきがかわる。","The scenery changes with the seasons."],
    ["に対して","にたいして","ni taishite","toward / regarding","質問に対して答える。","しつもんにたいしてこたえる。","I answer the question."],
    ["として","","to shite","as (in the role of)","代表として参加する。","だいひょうとしてさんかする。","I participate as a representative."],
    ["にとって","","ni totte","for / to (from the view of)","私にとって難しい問題だ。","わたしにとってむずかしいもんだいだ。","It's a hard problem for me."],
    ["とともに","","to tomo ni","together with / as","時間とともに変わる。","じかんとともにかわる。","It changes with time."],
    ["に比べて","にくらべて","ni kurabete","compared to","去年に比べて暑い。","きょねんにくらべてあつい。","It's hot compared to last year."],
    ["に関する","にかんする","ni kansuru","regarding / related to","環境に関する本を読む。","かんきょうにかんするほんをよむ。","I read a book about the environment."],
  ]},

  "n4-phrases-daily": { level: "N4", pos: "Expression", rows: [
    ["お久しぶりです","おひさしぶりです","o-hisashiburi desu","\"long time no see\"","お久しぶりです。お元気でしたか。","おひさしぶりです。おげんきでしたか。","Long time no see. How have you been?"],
    ["おかげさまで","","okagesama de","\"thanks to you\" (I'm well)","おかげさまで元気です。","おかげさまでげんきです。","I'm well, thank you."],
    ["お疲れさまです","おつかれさまです","o-tsukaresama desu","\"thanks for your hard work\" (greeting)","お疲れさまです。お先に失礼します。","おつかれさまです。おさきにしつれいします。","Good work today. I'm heading out."],
    ["いってきます","","ittekimasu","\"I'm off (and will be back)\"","いってきます。","いってきます。","I'm leaving now."],
    ["いってらっしゃい","","itterasshai","\"take care / see you\" (to one leaving)","いってらっしゃい。","いってらっしゃい。","Take care; see you later."],
    ["ただいま","","tadaima","\"I'm home / I'm back\"","ただいま。","ただいま。","I'm home."],
    ["おかえりなさい","","okaerinasai","\"welcome back\"","おかえりなさい。","おかえりなさい。","Welcome home."],
    ["ごちそうさまでした","","gochisousama deshita","\"thanks for the meal\" (after eating)","ごちそうさまでした。","ごちそうさまでした。","Thank you for the meal."],
    ["お先に失礼します","おさきにしつれいします","osaki ni shitsurei shimasu","\"excuse me for leaving first\"","お先に失礼します。","おさきにしつれいします。","Excuse me, I'm leaving first."],
    ["なるほど","","naruhodo","\"I see / that makes sense\"","なるほど、そういうことですか。","なるほど、そういうことですか。","I see, so that's what it is."],
    ["別に","べつに","betsu ni","\"not really / nothing in particular\"","「どうしたの?」「別に。」","「どうしたの?」「べつに。」","\"What's wrong?\" \"Nothing.\""],
    ["とりあえず","","toriaezu","\"for now / first of all\"","とりあえずビールをください。","とりあえずビールをください。","A beer to start, please."],
    ["お大事に","おだいじに","o-daiji ni","\"take care\" (to someone unwell)","風邪ですか。お大事に。","かぜですか。おだいじに。","You have a cold? Take care."],
    ["そろそろ","","sorosoro","\"about time to / soon\"","そろそろ帰りましょう。","そろそろかえりましょう。","It's about time we headed home."],
    ["まあまあ","","maamaa","\"so-so / not bad\"","「調子はどう?」「まあまあです。」","「ちょうしはどう?」「まあまあです。」","\"How are things?\" \"So-so.\""],
    ["どういたしまして","","dou itashimashite","\"you're welcome\"","「ありがとう。」「どういたしまして。」","「ありがとう。」「どういたしまして。」","\"Thanks.\" \"You're welcome.\""],
  ]},

  "n4-phrases-opinion": { level: "N4", pos: "Expression", rows: [
    ["〜と思います","","to omoimasu","\"I think (that)\"","それはいい考えだと思います。","それはいいかんがえだとおもいます。","I think that's a good idea."],
    ["〜じゃないかと思う","","ja nai ka to omou","\"I think maybe / isn't it that ~?\"","少し高いんじゃないかと思う。","すこしたかいんじゃないかとおもう。","I think it might be a bit expensive."],
    ["私の意見では","わたしのいけんでは","watashi no iken de wa","\"in my opinion\"","私の意見では、賛成です。","わたしのいけんでは、さんせいです。","In my opinion, I'm in favor."],
    ["〜かもしれません","","kamo shiremasen","\"it might be that ~\"","そうかもしれません。","そうかもしれません。","That might be so."],
    ["〜の方がいい","〜のほうがいい","no hou ga ii","\"~ is better\"","こっちの方がいいと思う。","こっちのほうがいいとおもう。","I think this one is better."],
    ["賛成です","さんせいです","sansei desu","\"I agree\"","その案に賛成です。","そのあんにさんせいです。","I agree with that proposal."],
    ["反対です","はんたいです","hantai desu","\"I disagree / I'm against it\"","私はその意見に反対です。","わたしはそのいけんにはんたいです。","I'm against that opinion."],
    ["確かに","たしかに","tashika ni","\"indeed / certainly (that's true)\"","確かにそうですね。","たしかにそうですね。","Indeed, that's true."],
    ["〜と言えば","〜といえば","to ieba","\"speaking of ~\"","旅行と言えば、京都がおすすめだ。","りょこうといえば、きょうとがおすすめだ。","Speaking of travel, I recommend Kyoto."],
    ["たぶん","","tabun","\"probably / maybe\"","たぶん大丈夫だと思います。","たぶんだいじょうぶだとおもいます。","I think it's probably fine."],
    ["〜気がする","〜きがする","ki ga suru","\"I get the feeling that ~\"","うまくいく気がする。","うまくいくきがする。","I have a feeling it'll go well."],
    ["〜べきだと思う","〜べきだとおもう","beki da to omou","\"I think (one) should ~\"","もっと休むべきだと思う。","もっとやすむべきだとおもう。","I think you should rest more."],
    ["正直に言うと","しょうじきにいうと","shoujiki ni iu to","\"to be honest\"","正直に言うと、あまり好きじゃない。","しょうじきにいうと、あまりすきじゃない。","To be honest, I don't really like it."],
    ["どちらかと言うと","どちらかというと","dochira ka to iu to","\"if anything / rather\"","どちらかと言うと夏が好きだ。","どちらかというとなつがすきだ。","If anything, I prefer summer."],
    ["そうは思いません","そうはおもいません","sou wa omoimasen","\"I don't think so\"","失礼ですが、そうは思いません。","しつれいですが、そうはおもいません。","With respect, I don't think so."],
  ]},

  "n4-phrases-request": { level: "N4", pos: "Expression", rows: [
    ["〜てください","","te kudasai","\"please do ~\"","ドアを閉めてください。","ドアをしめてください。","Please close the door."],
    ["〜てくださいませんか","","te kudasaimasen ka","\"could you please ~?\" (polite)","手伝ってくださいませんか。","てつだってくださいませんか。","Could you please help me?"],
    ["〜ていただけますか","","te itadakemasu ka","\"could you ~?\" (very polite)","写真を撮っていただけますか。","しゃしんをとっていただけますか。","Could you take a photo?"],
    ["〜てもらえますか","","te moraemasu ka","\"can you ~ for me?\"","塩を取ってもらえますか。","しおをとってもらえますか。","Can you pass me the salt?"],
    ["〜てくれない?","","te kurenai","\"can you ~?\" (casual)","ちょっと手伝ってくれない?","ちょっとてつだってくれない?","Can you help me for a sec?"],
    ["〜をお願いします","〜をおねがいします","o onegai shimasu","\"~, please\" (requesting)","これをお願いします。","これをおねがいします。","This one, please."],
    ["〜をください","","o kudasai","\"please give me ~\"","メニューをください。","メニューをください。","The menu, please."],
    ["〜てもいいですか","","te mo ii desu ka","\"may I ~?\"","ここに入ってもいいですか。","ここにはいってもいいですか。","May I come in here?"],
    ["〜させてください","","sasete kudasai","\"please let me ~\"","私に行かせてください。","わたしにいかせてください。","Please let me go."],
    ["ちょっといいですか","","chotto ii desu ka","\"do you have a moment?\"","すみません、ちょっといいですか。","すみません、ちょっといいですか。","Excuse me, do you have a moment?"],
    ["お手数ですが","おてすうですが","otesuu desu ga","\"sorry to trouble you, but ~\"","お手数ですが、確認してください。","おてすうですが、かくにんしてください。","Sorry to bother you, but please check it."],
    ["悪いけど","わるいけど","warui kedo","\"sorry, but ~\" (casual)","悪いけど、静かにして。","わるいけど、しずかにして。","Sorry, but please be quiet."],
    ["〜てほしいんですが","","te hoshii n desu ga","\"I'd like you to ~\"","もう少し説明してほしいんですが。","もうすこしせつめいしてほしいんですが。","I'd like you to explain a bit more."],
    ["申し訳ないんですが","もうしわけないんですが","moushiwake nai n desu ga","\"I'm sorry, but ~\" (request)","申し訳ないんですが、お願いできますか。","もうしわけないんですが、おねがいできますか。","I'm sorry, but could you do this?"],
    ["〜ないでください","","naide kudasai","\"please don't ~\"","ここで触らないでください。","ここでさわらないでください。","Please don't touch this here."],
  ]},

  "n3-phrases-connecting": { level: "N3", pos: "Expression", rows: [
    ["それで","","sorede","\"and so / that's why\"","それで、どうなりましたか。","それで、どうなりましたか。","And so, what happened?"],
    ["そこで","","sokode","\"so / and so (took action)\"","そこで、私が提案した。","そこで、わたしがていあんした。","So then, I made a suggestion."],
    ["ところで","","tokorode","\"by the way\"","ところで、話は変わりますが。","ところで、はなしはかわりますが。","By the way, to change the subject..."],
    ["それに","","soreni","\"moreover / besides\"","安いし、それにおいしい。","やすいし、それにおいしい。","It's cheap; besides, it's tasty."],
    ["しかし","","shikashi","\"however\"","しかし、問題が残っている。","しかし、もんだいがのこっている。","However, a problem remains."],
    ["ただし","","tadashi","\"however / provided that\"","入場無料。ただし、子供のみ。","にゅうじょうむりょう。ただし、こどものみ。","Admission free. However, children only."],
    ["つまり","","tsumari","\"in other words\"","つまり、君も賛成なんだね。","つまり、きみもさんせいなんだね。","In other words, you agree too."],
    ["たとえば","","tatoeba","\"for example\"","たとえば、これはどうですか。","たとえば、これはどうですか。","For example, how about this?"],
    ["一方で","いっぽうで","ippou de","\"on the other hand\"","便利だ。一方で、危険もある。","べんりだ。いっぽうで、きけんもある。","It's convenient. On the other hand, there's danger too."],
    ["その結果","そのけっか","sono kekka","\"as a result\"","努力した。その結果、成功した。","どりょくした。そのけっか、せいこうした。","I worked hard. As a result, I succeeded."],
    ["というのは","","to iu no wa","\"that's because / the reason is\"","遅れた。というのは、急用ができたからだ。","おくれた。というのは、きゅうようができたからだ。","I was late — that's because something urgent came up."],
    ["それにしても","","sore ni shite mo","\"even so / nonetheless\"","それにしても、暑いね。","それにしても、あついね。","Even so, it sure is hot."],
    ["ちなみに","","chinami ni","\"incidentally / for reference\"","ちなみに、料金は無料です。","ちなみに、りょうきんはむりょうです。","Incidentally, it's free of charge."],
    ["そのため","","sono tame","\"for that reason / therefore\"","事故があった。そのため、電車が遅れた。","じこがあった。そのため、でんしゃがおくれた。","There was an accident. Therefore, the train was delayed."],
    ["要するに","ようするに","you suru ni","\"in short / to sum up\"","要するに、準備不足だった。","ようするに、じゅんびぶそくだった。","In short, we were underprepared."],
    ["けれども","","keredomo","\"however / but\" (a bit formal)","行きたい。けれども、時間がない。","いきたい。けれども、じかんがない。","I want to go, but I don't have time."],
  ]},

  "n3-phrases-feelings": { level: "N3", pos: "Expression", rows: [
    ["嬉しい","うれしい","ureshii","\"happy / glad\"","合格できて本当に嬉しい。","ごうかくできてほんとうにうれしい。","I'm really happy I passed."],
    ["楽しみにしている","たのしみにしている","tanoshimi ni shite iru","\"looking forward to\"","旅行を楽しみにしている。","りょこうをたのしみにしている。","I'm looking forward to the trip."],
    ["残念ながら","ざんねんながら","zannen nagara","\"unfortunately / regrettably\"","残念ながら、参加できません。","ざんねんながら、さんかできません。","Unfortunately, I can't attend."],
    ["がっかりする","","gakkari suru","\"to be disappointed\"","結果にがっかりした。","けっかにがっかりした。","I was disappointed with the result."],
    ["感動する","かんどうする","kandou suru","\"to be moved / touched\"","その映画に感動した。","そのえいがにかんどうした。","I was moved by that movie."],
    ["安心する","あんしんする","anshin suru","\"to feel relieved\"","連絡が来て安心した。","れんらくがきてあんしんした。","I felt relieved when I got the message."],
    ["心配する","しんぱいする","shinpai suru","\"to worry\"","試験の結果が心配だ。","しけんのけっかがしんぱいだ。","I'm worried about the exam results."],
    ["緊張する","きんちょうする","kinchou suru","\"to be nervous\"","面接でとても緊張した。","めんせつでとてもきんちょうした。","I was very nervous in the interview."],
    ["びっくりする","","bikkuri suru","\"to be surprised\"","突然のニュースにびっくりした。","とつぜんのニュースにびっくりした。","I was surprised by the sudden news."],
    ["困っている","こまっている","komatte iru","\"to be troubled / in a bind\"","道に迷って困っている。","みちにまよってこまっている。","I'm lost and don't know what to do."],
    ["〜てよかった","","te yokatta","\"I'm glad that ~\"","あなたに会えてよかった。","あなたにあえてよかった。","I'm glad I got to meet you."],
    ["うらやましい","","urayamashii","\"envious / jealous\"","君がうらやましい。","きみがうらやましい。","I envy you."],
    ["恥ずかしい","はずかしい","hazukashii","\"embarrassed / ashamed\"","みんなの前で間違えて恥ずかしい。","みんなのまえでまちがえてはずかしい。","I'm embarrassed for making a mistake in front of everyone."],
    ["もったいない","","mottainai","\"wasteful / a shame\"","まだ使えるのに捨てるのはもったいない。","まだつかえるのにすてるのはもったいない。","It's a waste to throw it out when it still works."],
    ["感謝している","かんしゃしている","kansha shite iru","\"to be grateful\"","心から感謝しています。","こころからかんしゃしています。","I'm grateful from the bottom of my heart."],
    ["楽しかった","たのしかった","tanoshikatta","\"it was fun\"","今日は本当に楽しかった。","きょうはほんとうにたのしかった。","Today was really fun."],
  ]},

  "n3-phrases-formal": { level: "N3", pos: "Expression", rows: [
    ["失礼ですが","しつれいですが","shitsurei desu ga","\"excuse me, but ~\"","失礼ですが、お名前は?","しつれいですが、おなまえは?","Excuse me, but your name is?"],
    ["恐れ入りますが","おそれいりますが","osore irimasu ga","\"I'm sorry to trouble you, but\"","恐れ入りますが、少々お待ちください。","おそれいりますが、しょうしょうおまちください。","Sorry to trouble you, but please wait a moment."],
    ["お忙しいところ","おいそがしいところ","o-isogashii tokoro","\"(sorry) while you're busy\"","お忙しいところ、すみません。","おいそがしいところ、すみません。","Sorry to bother you when you're busy."],
    ["よろしければ","","yoroshikereba","\"if you'd like\"","よろしければ、ご案内します。","よろしければ、ごあんないします。","If you'd like, I'll show you around."],
    ["差し支えなければ","さしつかえなければ","sashitsukae nakereba","\"if it's not inconvenient\"","差し支えなければ、ご連絡先を。","さしつかえなければ、ごれんらくさきを。","If you don't mind, your contact details, please."],
    ["お言葉に甘えて","おことばにあまえて","o-kotoba ni amaete","\"taking you up on your kind offer\"","お言葉に甘えて、いただきます。","おことばにあまえて、いただきます。","I'll gladly accept your kind offer."],
    ["おかげさまで","","okagesama de","\"thanks to you\"","おかげさまで、うまくいきました。","おかげさまで、うまくいきました。","Thanks to you, it went well."],
    ["ご無沙汰しております","ごぶさたしております","gobusata shite orimasu","\"it's been a long time\" (formal)","ご無沙汰しております。","ごぶさたしております。","It's been a while."],
    ["申し訳ございません","もうしわけございません","moushiwake gozaimasen","\"I'm very sorry\"","ご迷惑をおかけし、申し訳ございません。","ごめいわくをおかけし、もうしわけございません。","I'm very sorry for the inconvenience."],
    ["お手数をおかけします","おてすうをおかけします","otesuu o okake shimasu","\"sorry for the trouble I'm causing\"","お手数をおかけしますが、よろしくお願いします。","おてすうをおかけしますが、よろしくおねがいします。","Sorry for the trouble; thank you in advance."],
    ["〜と申します","〜ともうします","to moushimasu","\"my name is ~\" (humble)","ABC社の田中と申します。","エービーシーしゃのたなかともうします。","I'm Tanaka from ABC Company."],
    ["失礼いたします","しつれいいたします","shitsurei itashimasu","\"excuse me\" (formal, entering/leaving)","それでは、失礼いたします。","それでは、しつれいいたします。","Well then, please excuse me."],
    ["ご迷惑をおかけしました","ごめいわくをおかけしました","go-meiwaku o okake shimashita","\"sorry for the inconvenience caused\"","この度はご迷惑をおかけしました。","このたびはごめいわくをおかけしました。","I apologize for the inconvenience this time."],
    ["何卒よろしくお願いします","なにとぞよろしくおねがいします","nanitozo yoroshiku onegai shimasu","\"I sincerely ask for your kind help\"","何卒よろしくお願いします。","なにとぞよろしくおねがいします。","I humbly ask for your kind consideration."],
    ["かしこまりました","","kashikomarimashita","\"certainly / understood\" (polite)","かしこまりました。","かしこまりました。","Certainly."],
  ]},

  "n2-phrases-business": { level: "N2", pos: "Expression", rows: [
    ["お世話になっております","おせわになっております","o-sewa ni natte orimasu","\"thank you for your continued business\"","いつもお世話になっております。","いつもおせわになっております。","Thank you for your continued support."],
    ["承知いたしました","しょうちいたしました","shouchi itashimashita","\"understood / certainly\" (humble)","承知いたしました。手配します。","しょうちいたしました。てはいします。","Understood. I'll arrange it."],
    ["確認させていただきます","かくにんさせていただきます","kakunin sasete itadakimasu","\"allow me to confirm\"","内容を確認させていただきます。","ないようをかくにんさせていただきます。","Allow me to confirm the details."],
    ["お手すきの際に","おてすきのさいに","o-tesuki no sai ni","\"when you have a moment\"","お手すきの際にご連絡ください。","おてすきのさいにごれんらくください。","Please contact me when you have a moment."],
    ["ご検討ください","ごけんとうください","go-kentou kudasai","\"please consider it\"","前向きにご検討ください。","まえむきにごけんとうください。","Please give it your positive consideration."],
    ["折り返しご連絡します","おりかえしごれんらくします","orikaeshi go-renraku shimasu","\"I'll get back to you\"","折り返しご連絡いたします。","おりかえしごれんらくいたします。","I'll call you back."],
    ["お世話になります","おせわになります","o-sewa ni narimasu","\"thank you in advance\" (new contact)","この度はお世話になります。","このたびはおせわになります。","Thank you for your help on this matter."],
    ["恐れ入りますが","おそれいりますが","osore irimasu ga","\"I'm sorry to trouble you, but\"","恐れ入りますが、ご確認をお願いします。","おそれいりますが、ごかくにんをおねがいします。","Sorry to trouble you, but please confirm."],
    ["お忙しいところ恐縮ですが","おいそがしいところきょうしゅくですが","o-isogashii tokoro kyoushuku desu ga","\"sorry to bother you when busy, but\"","お忙しいところ恐縮ですが、お願いします。","おいそがしいところきょうしゅくですが、おねがいします。","Sorry to bother you when you're busy, but please."],
    ["ご査収ください","ごさしゅうください","go-sashuu kudasai","\"please find enclosed and review\"","資料を添付します。ご査収ください。","しりょうをてんぷします。ごさしゅうください。","I've attached the documents; please review them."],
    ["取り急ぎ","とりいそぎ","toriisogi","\"just a quick note / in haste\"","取り急ぎ、お礼まで。","とりいそぎ、おれいまで。","Just a quick note of thanks for now."],
    ["〜の件ですが","〜のけんですが","no ken desu ga","\"regarding the matter of ~\"","先日の件ですが、いかがでしょうか。","せんじつのけんですが、いかがでしょうか。","Regarding the other day's matter, how is it going?"],
    ["お時間をいただけますか","おじかんをいただけますか","o-jikan o itadakemasu ka","\"could I have your time?\"","少しお時間をいただけますか。","すこしおじかんをいただけますか。","Could you spare me a moment?"],
    ["申し訳ございませんが","もうしわけございませんが","moushiwake gozaimasen ga","\"I'm terribly sorry, but ~\"","申し訳ございませんが、変更をお願いします。","もうしわけございませんが、へんこうをおねがいします。","I'm very sorry, but please make a change."],
    ["お疲れ様です","おつかれさまです","o-tsukaresama desu","\"thank you for your work\" (workplace greeting)","お疲れ様です。会議の件です。","おつかれさまです。かいぎのけんです。","Hello. It's about the meeting."],
    ["何卒よろしくお願い申し上げます","なにとぞよろしくおねがいもうしあげます","nanitozo yoroshiku onegai moushiagemasu","\"I humbly request your kind help\"","何卒よろしくお願い申し上げます。","なにとぞよろしくおねがいもうしあげます。","I sincerely ask for your kind consideration."],
  ]},

  "n2-phrases-written": { level: "N2", pos: "Expression", rows: [
    ["〜である","","de aru","plain written copula \"to be\"","これは重大な問題である。","これはじゅうだいなもんだいである。","This is a serious problem."],
    ["〜と考えられる","〜とかんがえられる","to kangaerareru","\"it is thought that ~\"","影響があると考えられる。","えいきょうがあるとかんがえられる。","It is thought that there is an effect."],
    ["〜によると","","ni yoru to","\"according to ~\"","報告によると、増加している。","ほうこくによると、ぞうかしている。","According to the report, it is increasing."],
    ["〜に基づき","〜にもとづき","ni motozuki","\"based on ~\" (written)","データに基づき分析する。","データにもとづきぶんせきする。","We analyze it based on the data."],
    ["まず","","mazu","\"first (of all)\"","まず、背景を説明する。","まず、はいけいをせつめいする。","First, I'll explain the background."],
    ["次に","つぎに","tsugi ni","\"next\"","次に、結果を述べる。","つぎに、けっかをのべる。","Next, I'll state the results."],
    ["さらに","","sara ni","\"furthermore / moreover\"","さらに、別の問題もある。","さらに、べつのもんだいもある。","Furthermore, there is another problem."],
    ["したがって","","shitagatte","\"therefore / consequently\"","したがって、結論は明らかだ。","したがって、けつろんはあきらかだ。","Therefore, the conclusion is clear."],
    ["一方","いっぽう","ippou","\"on the other hand / meanwhile\"","一方、反対意見もある。","いっぽう、はんたいいけんもある。","On the other hand, there are objections too."],
    ["なぜなら〜からだ","","nazenara ~kara da","\"this is because ~\"","なぜなら、需要が高いからだ。","なぜなら、じゅようがたかいからだ。","This is because demand is high."],
    ["〜と言える","〜といえる","to ieru","\"it can be said that ~\"","これは成功と言える。","これはせいこうといえる。","This can be called a success."],
    ["〜に過ぎない","〜にすぎない","ni suginai","\"is merely / no more than\"","それは一例に過ぎない。","それはいちれいにすぎない。","That is merely one example."],
    ["以上のことから","いじょうのことから","ijou no koto kara","\"from the above\"","以上のことから、こう結論する。","いじょうのことから、こうけつろんする。","From the above, I conclude as follows."],
    ["〜が挙げられる","〜があげられる","ga agerareru","\"~ can be cited / given\"","例として次が挙げられる。","れいとしてつぎがあげられる。","The following can be cited as an example."],
    ["〜と言われている","〜といわれている","to iwarete iru","\"it is said that ~\"","健康に良いと言われている。","けんこうによいといわれている。","It is said to be good for your health."],
  ]},

  "n1-phrases-formal": { level: "N1", pos: "Expression", rows: [
    ["〜に他ならない","〜にほかならない","ni hoka naranai","\"is nothing but / precisely ~\"","これは努力の賜物に他ならない。","これはどりょくのたまものにほかならない。","This is nothing but the fruit of hard work."],
    ["〜を余儀なくされる","〜をよぎなくされる","o yogi naku sareru","\"to be forced to ~\"","計画の変更を余儀なくされた。","けいかくのへんこうをよぎなくされた。","We were forced to change the plan."],
    ["〜に堪えない","〜にたえない","ni taenai","\"cannot bear ~ / unbearable\"","その光景は見るに堪えない。","そのこうけいはみるにたえない。","That sight is unbearable to watch."],
    ["〜と言わざるを得ない","〜といわざるをえない","to iwazaru o enai","\"cannot but say that ~\"","それは失敗と言わざるを得ない。","それはしっぱいといわざるをえない。","One cannot but call it a failure."],
    ["〜には当たらない","〜にはあたらない","ni wa ataranai","\"does not warrant ~\"","それほど驚くには当たらない。","それほどおどろくにはあたらない。","It doesn't warrant that much surprise."],
    ["〜を踏まえて","〜をふまえて","o fumaete","\"based on / in light of ~\"","現状を踏まえて判断する。","げんじょうをふまえてはんだんする。","I'll judge based on the current situation."],
    ["〜の感を否めない","〜のかんをいなめない","no kan o inamenai","\"cannot deny a sense of ~\"","時代遅れの感を否めない。","じだいおくれのかんをいなめない。","One cannot deny a sense of being outdated."],
    ["〜に資する","〜にしする","ni shisuru","\"to contribute to ~\" (formal)","社会の発展に資する。","しゃかいのはってんにしする。","It contributes to society's development."],
    ["〜を以て","〜をもって","o motte","\"by means of / as of ~\"","書面を以て通知する。","しょめんをもってつうちする。","We will notify you in writing."],
    ["〜に鑑みて","〜にかんがみて","ni kangamite","\"in view of / in light of ~\"","状況に鑑みて中止する。","じょうきょうにかんがみてちゅうしする。","In view of the situation, we'll cancel."],
    ["〜は言うまでもない","〜はいうまでもない","wa iu made mo nai","\"it goes without saying that ~\"","重要なのは言うまでもない。","じゅうようなのはいうまでもない。","It goes without saying that it's important."],
    ["〜を禁じ得ない","〜をきんじえない","o kinjienai","\"cannot suppress (a feeling) ~\"","怒りを禁じ得ない。","いかりをきんじえない。","I cannot suppress my anger."],
    ["〜の感がある","〜のかんがある","no kan ga aru","\"there is a sense of ~\"","やや唐突の感がある。","ややとうとつのかんがある。","There's a somewhat abrupt feel to it."],
    ["〜に越したことはない","〜にこしたことはない","ni koshita koto wa nai","\"there's nothing better than ~\"","用心するに越したことはない。","ようじんするにこしたことはない。","There's nothing better than being cautious."],
    ["〜の限りである","〜のかぎりである","no kagiri de aru","\"to be the utmost / extremely ~\"","お会いできて光栄の限りである。","おあいできてこうえいのかぎりである。","It is the greatest honor to meet you."],
  ]},

  "n1-phrases-nuanced": { level: "N1", pos: "Expression", rows: [
    ["〜というか","","to iu ka","\"or rather / how should I put it\"","嫌というか、苦手なんだ。","いやというか、にがてなんだ。","It's not that I hate it — more that I'm bad at it."],
    ["なんというか","","nan to iu ka","\"how should I say it...\"","なんというか、複雑な気持ちだ。","なんというか、ふくざつなきもちだ。","How should I put it — it's a complicated feeling."],
    ["〜んだけど","","n da kedo","trailing \"~ but...\" (leaving it unsaid)","本当は行きたいんだけど…。","ほんとうはいきたいんだけど…。","I'd actually like to go, but..."],
    ["〜かな(と)","","kana (to)","\"I wonder / maybe\" (softening)","それはちょっと違うかな。","それはちょっとちがうかな。","That's a little off, I think."],
    ["〜じゃない?","","ja nai","\"isn't it?\" (seeking agreement)","それでいいんじゃない?","それでいいんじゃない?","That's fine, isn't it?"],
    ["〜わけだ","","wake da","\"so that means ~ / no wonder\"","つまり、君も来るわけだ。","つまり、きみもくるわけだ。","So that means you're coming too."],
    ["〜ってこと?","","tte koto","\"so you mean ~?\"","じゃあ、中止ってこと?","じゃあ、ちゅうしってこと?","So you mean it's canceled?"],
    ["〜にしても","","ni shite mo","\"even so / even if ~\"","高いにしても、買う価値はある。","たかいにしても、かうかちはある。","Even if it's expensive, it's worth buying."],
    ["〜ないこともない","","nai koto mo nai","\"it's not that ~ can't (hedge)\"","行けないこともない。","いけないこともない。","It's not like I can't go."],
    ["一応","いちおう","ichiou","\"just in case / more or less\"","一応、確認しておく。","いちおう、かくにんしておく。","I'll check just to be sure."],
    ["何となく","なんとなく","nan to naku","\"somehow / vaguely\"","何となく分かる気がする。","なんとなくわかるきがする。","I sort of feel like I understand."],
    ["強いて言えば","しいていえば","shiite ieba","\"if I had to say\"","強いて言えば、青が好きだ。","しいていえば、あおがすきだ。","If I had to pick, I like blue."],
    ["ぶっちゃけ","","bucchake","\"to be blunt / honestly\" (slang)","ぶっちゃけ、面倒くさい。","ぶっちゃけ、めんどうくさい。","Honestly, it's a pain."],
    ["それはそうと","","sore wa sou to","\"anyway / that aside\"","それはそうと、昼ご飯は?","それはそうと、ひるごはんは?","Anyway, what about lunch?"],
    ["〜とでも言おうか","〜とでもいおうか","to demo iou ka","\"one might call it ~ / so to speak\"","これは運命とでも言おうか。","これはうんめいとでもいおうか。","This is, one might say, fate."],
  ]},
};

let total = 0;
for (const [key, def] of Object.entries(DECKS)) {
  const arr = def.rows.map(mk(def.level, def.pos));
  const json = JSON.stringify(arr, null, 2);
  fs.writeFileSync(path.join(DATA, key + ".json"), json);
  fs.writeFileSync(path.join(DATA, key + ".js"),
    `// Auto-generated fallback for file:// (when fetch is blocked). Source: ${key}.json\n` +
    `window.DECKS=window.DECKS||{};\nwindow.DECKS[${JSON.stringify(key)}]=${json};\n`);
  console.log(`${key}: ${arr.length}`);
  total += arr.length;
}
console.log("Phrases/particles TOTAL entries:", total);
